# Role with permissions for frontend access
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: frontend-role
  namespace: workloads
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]
---
# RoleBinding for Frontend Service Account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: frontend-rolebinding
  namespace: workloads
subjects:
- kind: ServiceAccount
  name: frontend-sa
  namespace: workloads
roleRef:
  kind: Role
  name: frontend-role
  apiGroup: rbac.authorization.k8s.io
