# Role with permissions for backend access
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backend-role
  namespace: workloads
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
---
# RoleBinding for Backend Service Account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-rolebinding
  namespace: workloads
subjects:
- kind: ServiceAccount
  name: backend-sa
  namespace: workloads
roleRef:
  kind: Role
  name: backend-role
  apiGroup: rbac.authorization.k8s.io
