name: Build and Push Docker Images

on:
  repository_dispatch:
    types: [docker-build]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Cod
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Backend Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/stock-backend:latest ./backend
          docker push $ECR_REGISTRY/stock-backend:latest

      - name: Build and Push Frontend Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/stock-frontend:latest ./frontend
          docker push $ECR_REGISTRY/stock-frontend:latest

      - name: Build and Push Redis Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/stock-redis:latest ./cache
          docker push $ECR_REGISTRY/stock-redis:latest

