name: docker-build-push

on:
  repository_dispatch:
    types: [docker-build-push]
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'cache/**'
      - '.github/workflows/docker-build-push.yml'

jobs:
  docker:
    runs-on: ubuntu-latest

    env:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Backend Image
      - name: Build and push backend Docker image
        run: |
          IMAGE="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/stock-backend:latest"
          echo "Building backend image with tag $IMAGE"
          docker build -t $IMAGE ./backend
          docker push $IMAGE

      # Frontend Image
      - name: Build and push frontend Docker image
        run: |
          IMAGE="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/stock-frontend:latest"
          echo "Building frontend image with tag $IMAGE"
          docker build -t $IMAGE ./frontend
          docker push $IMAGE

      # Cache Image
      - name: Build and push cache Docker image
        run: |
          IMAGE="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/stock-cache:latest"
          echo "Building cache image with tag $IMAGE"
          docker build -t $IMAGE ./cache
          docker push $IMAGE
