name: install-flux

on:
  repository_dispatch:
    types: [flux-install]

jobs:
  install-flux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Set up kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Update kubeconfig for EKS cluster
        run: aws eks --region us-east-2 update-kubeconfig --name my-eks-cluster

      - name: Create flux-system namespace
        run: kubectl create namespace flux-system || true

      - name: Install Flux CLI
        run: |
          curl -s https://fluxcd.io/install.sh | sudo bash

      - name: Bootstrap FluxCD
        run: |
          flux bootstrap github \
            --owner=oyedeloy \
            --repository=stock-price-app \
            --branch=main \
            --path=clusters/my-cluster \
            --personal
